use std::error::Error;

use serde::Serialize;
use thiserror::Error;

use crate::backend::{Database, QueryParams};
use crate::db::{extract_i64, extract_string};

use crate::query_builders::validate_regex_patterns;

#[derive(Error, Debug)]
pub enum DuplicatesError {
    #[error("Duplicates query failed: {message}")]
    QueryFailed { message: String },
}

/// A function that has a duplicate implementation (same AST or source hash)
#[derive(Debug, Clone, Serialize)]
pub struct DuplicateFunction {
    pub hash: String,
    pub module: String,
    pub name: String,
    pub arity: i64,
    pub line: i64,
    pub file: String,
}

pub fn find_duplicates(
    db: &dyn Database,
    module_pattern: Option<&str>,
    use_regex: bool,
    use_exact: bool,
    exclude_generated: bool,
) -> Result<Vec<DuplicateFunction>, Box<dyn Error>> {
    validate_regex_patterns(use_regex, &[module_pattern])?;

    // Choose hash field based on exact flag
    let hash_field = if use_exact { "source_sha" } else { "ast_sha" };

    // Build generated filter - this is applied during query
    let generated_filter = if exclude_generated {
        " AND (generated_by IS NONE)"
    } else {
        ""
    };

    // Query to get all clauses with non-empty hash values
    // Note: Module filter is applied AFTER finding duplicates in Rust, to ensure
    // we correctly identify duplicate pairs before filtering.
    let query = format!("SELECT {} as hash, module_name as module, function_name as name, arity, line, source_file as file FROM clauses WHERE {} != \"\"{} ORDER BY hash, module, name, arity",
        hash_field, hash_field, generated_filter
    );

    let params = QueryParams::new();

    let result = db
        .execute_query(&query, params)
        .map_err(|e| DuplicatesError::QueryFailed {
            message: e.to_string(),
        })?;

    // SurrealDB returns columns in alphabetical order by header name, not SELECT order.
    // Find column indices by name.
    let headers = result.headers();
    let hash_idx = headers.iter().position(|h| h == "hash").unwrap_or(0);
    let module_idx = headers.iter().position(|h| h == "module").unwrap_or(1);
    let name_idx = headers.iter().position(|h| h == "name").unwrap_or(2);
    let arity_idx = headers.iter().position(|h| h == "arity").unwrap_or(3);
    let line_idx = headers.iter().position(|h| h == "line").unwrap_or(4);
    let file_idx = headers.iter().position(|h| h == "file").unwrap_or(5);

    let mut all_items = Vec::new();
    for row in result.rows() {
        if row.len() >= 6 {
            let hash = row.get(hash_idx).and_then(|v| extract_string(v)).unwrap_or_default();
            let module = row.get(module_idx).and_then(|v| extract_string(v)).unwrap_or_default();
            let name = row.get(name_idx).and_then(|v| extract_string(v)).unwrap_or_default();
            let arity = row.get(arity_idx).map(|v| extract_i64(v, 0)).unwrap_or(0);
            let line = row.get(line_idx).map(|v| extract_i64(v, 0)).unwrap_or(0);
            let file = row.get(file_idx).and_then(|v| extract_string(v)).unwrap_or_default();

            if !hash.is_empty() && !module.is_empty() && !name.is_empty() && !file.is_empty() {
                all_items.push(DuplicateFunction {
                    hash,
                    module,
                    name,
                    arity,
                    line,
                    file,
                });
            }
        }
    }

    // Filter to keep only hashes that appear more than once
    use std::collections::HashMap;
    let mut hash_counts: HashMap<String, usize> = HashMap::new();
    for item in &all_items {
        *hash_counts.entry(item.hash.clone()).or_insert(0) += 1;
    }

    // First filter to keep only hashes that appear more than once
    let duplicates: Vec<_> = all_items
        .into_iter()
        .filter(|item| hash_counts.get(&item.hash).map_or(false, |count| *count > 1))
        .collect();

    // Then apply module filter if provided
    let results = if let Some(pattern) = module_pattern {
        if use_regex {
            let regex = regex::Regex::new(pattern).map_err(|e| DuplicatesError::QueryFailed {
                message: format!("Invalid regex pattern: {}", e),
            })?;
            duplicates
                .into_iter()
                .filter(|item| regex.is_match(&item.module))
                .collect()
        } else {
            duplicates
                .into_iter()
                .filter(|item| item.module.contains(pattern))
                .collect()
        }
    } else {
        duplicates
    };

    Ok(results)
}

#[cfg(test)]
mod tests {
    use super::*;

    // The complex fixture contains duplicate test data for testing:
    // - AST duplicates: format_name/1 and format_display/1 (ast_hash_001)
    // - Source duplicates: validate/1 in Service and Repo (src_hash_001)
    // - Generated duplicates: __generated__/0 in Accounts and Controller (ast_hash_002, generated by phoenix)
    fn get_db() -> Box<dyn crate::backend::Database> {
        crate::test_utils::surreal_call_graph_db_complex()
    }

    // Build a database with additional edge-case clauses for mutation testing.
    //
    // Adds clauses that exercise the compound filter on line 82 and the
    // duplicate-count threshold on line 105:
    //
    // - Clauses with one empty field (module, name, or file) that share a
    //   duplicate hash — these must be excluded by the && filter. If any &&
    //   is mutated to ||, these rows leak through and change result counts.
    //
    // - A clause with a unique hash that appears exactly once — this must be
    //   excluded by the `> 1` threshold. If `>` is mutated to `>=`, this
    //   singleton leaks through.
    fn get_db_with_edge_cases() -> Box<dyn crate::backend::Database> {
        let db = get_db();

        // Clause with non-empty ast_sha but EMPTY module_name.
        // Shares ast_hash_001 so it would form a "triple" if not filtered out.
        // Catches && -> || between !hash.is_empty() and !module.is_empty().
        db.execute_query(
            r#"CREATE clauses:["", "phantom_no_module", 1, 200] SET
                module_name = "", function_name = "phantom_no_module", arity = 1,
                line = 200,
                source_file = "lib/phantom.ex", source_file_absolute = "",
                kind = "def",
                start_line = 200, end_line = 200,
                pattern = "", guard = NONE,
                source_sha = "", ast_sha = "ast_hash_001",
                complexity = 1, max_nesting_depth = 1,
                generated_by = NONE, macro_source = NONE;"#,
            QueryParams::new(),
        )
        .expect("Failed to insert clause with empty module");

        // Clause with non-empty ast_sha but EMPTY function_name.
        // Shares ast_hash_001 so it would form a "triple" if not filtered out.
        // Catches && -> || between !module.is_empty() and !name.is_empty().
        db.execute_query(
            r#"CREATE clauses:["MyApp.Phantom", "", 1, 201] SET
                module_name = "MyApp.Phantom", function_name = "", arity = 1,
                line = 201,
                source_file = "lib/phantom.ex", source_file_absolute = "",
                kind = "def",
                start_line = 201, end_line = 201,
                pattern = "", guard = NONE,
                source_sha = "", ast_sha = "ast_hash_001",
                complexity = 1, max_nesting_depth = 1,
                generated_by = NONE, macro_source = NONE;"#,
            QueryParams::new(),
        )
        .expect("Failed to insert clause with empty name");

        // Clause with non-empty ast_sha but EMPTY source_file.
        // Shares ast_hash_001 so it would form a "triple" if not filtered out.
        // Catches && -> || between !name.is_empty() and !file.is_empty().
        db.execute_query(
            r#"CREATE clauses:["MyApp.Phantom", "phantom_no_file", 1, 202] SET
                module_name = "MyApp.Phantom", function_name = "phantom_no_file", arity = 1,
                line = 202,
                source_file = "", source_file_absolute = "",
                kind = "def",
                start_line = 202, end_line = 202,
                pattern = "", guard = NONE,
                source_sha = "", ast_sha = "ast_hash_001",
                complexity = 1, max_nesting_depth = 1,
                generated_by = NONE, macro_source = NONE;"#,
            QueryParams::new(),
        )
        .expect("Failed to insert clause with empty file");

        // Clause with a UNIQUE ast_sha (appears only once) and all fields populated.
        // Tests the > 1 threshold on line 105 — a singleton must be excluded.
        // If > is mutated to >=, this row leaks into results.
        db.execute_query(
            r#"CREATE clauses:["MyApp.Phantom", "singleton_fn", 1, 203] SET
                module_name = "MyApp.Phantom", function_name = "singleton_fn", arity = 1,
                line = 203,
                source_file = "lib/phantom.ex", source_file_absolute = "",
                kind = "def",
                start_line = 203, end_line = 203,
                pattern = "", guard = NONE,
                source_sha = "", ast_sha = "unique_hash_only_one",
                complexity = 1, max_nesting_depth = 1,
                generated_by = NONE, macro_source = NONE;"#,
            QueryParams::new(),
        )
        .expect("Failed to insert singleton clause");

        db
    }

    // ===== Basic functionality tests =====

    #[test]
    fn test_find_duplicates_ast_hash_returns_expected_pairs() {
        let db = get_db();
        let result =
            find_duplicates(&*db, None, false, false, false).expect("Query should succeed");

        // Expect exactly 4 duplicates: 2 pairs with matching ast_sha and 2 generated
        assert_eq!(
            result.len(),
            4,
            "Should find 4 functions with duplicate AST hashes"
        );

        // Verify AST duplicates (ast_hash_001)
        let ast_dups: Vec<_> = result.iter().filter(|d| d.hash == "ast_hash_001").collect();
        assert_eq!(
            ast_dups.len(),
            2,
            "Should have 2 functions with ast_hash_001"
        );

        // Verify specific functions in AST pair
        assert!(
            ast_dups.iter().any(|d| d.module == "MyApp.Accounts"
                && d.name == "format_name"
                && d.arity == 1),
            "Should include MyApp.Accounts.format_name/1"
        );
        assert!(
            ast_dups.iter().any(|d| d.module == "MyApp.Controller"
                && d.name == "format_display"
                && d.arity == 1),
            "Should include MyApp.Controller.format_display/1"
        );

        // Verify generated duplicates (ast_hash_002)
        let gen_dups: Vec<_> = result.iter().filter(|d| d.hash == "ast_hash_002").collect();
        assert_eq!(gen_dups.len(), 2, "Should have 2 generated functions with ast_hash_002");
    }

    #[test]
    fn test_find_duplicates_source_hash_returns_exact_copies() {
        let db = get_db();
        let result = find_duplicates(&*db, None, false, true, false)
            .expect("Query should succeed");

        // Expect exactly 2 duplicates: 1 pair with matching source_sha
        assert_eq!(
            result.len(),
            2,
            "Should find 2 functions with duplicate source hashes"
        );

        // Both should have the same source_sha
        assert_eq!(result[0].hash, "src_hash_001");
        assert_eq!(result[1].hash, "src_hash_001");

        // Verify specific functions
        let modules: Vec<&str> = result.iter().map(|d| d.module.as_str()).collect();
        assert!(
            modules.contains(&"MyApp.Service"),
            "Should include MyApp.Service"
        );
        assert!(modules.contains(&"MyApp.Repo"), "Should include MyApp.Repo");

        // Verify function names
        let names: Vec<&str> = result.iter().map(|d| d.name.as_str()).collect();
        assert_eq!(
            names.iter().filter(|n| **n == "validate").count(),
            2,
            "Both should be validate functions"
        );
    }

    #[test]
    fn test_find_duplicates_exclude_generated_filters_correctly() {
        let db = get_db();

        // With generated
        let with_gen = find_duplicates(&*db, None, false, false, false)
            .expect("Query should succeed");

        // Without generated
        let without_gen = find_duplicates(&*db, None, false, false, true)
            .expect("Query should succeed");

        assert_eq!(
            with_gen.len(),
            4,
            "Should find 4 duplicates including generated"
        );
        assert_eq!(
            without_gen.len(),
            2,
            "Should find 2 duplicates excluding generated"
        );

        // Verify no generated functions in filtered results
        for dup in &without_gen {
            assert!(
                !dup.name.contains("__generated__"),
                "Should not contain generated functions: {}",
                dup.name
            );
        }
    }

    #[test]
    fn test_find_duplicates_module_filter_returns_matching_only() {
        let db = get_db();
        let result = find_duplicates(&*db, Some("Accounts"), false, false, false)
            .expect("Query should succeed");

        // Should find duplicates in or related to Accounts module
        assert!(!result.is_empty(), "Should find Accounts duplicates");

        for dup in &result {
            assert!(
                dup.module.contains("Accounts"),
                "All results should match Accounts filter: {}",
                dup.module
            );
        }
    }

    #[test]
    fn test_find_duplicates_ast_duplicates_with_excluded_generated() {
        let db = get_db();
        let result = find_duplicates(&*db, None, false, false, true)
            .expect("Query should succeed");

        // Should only find AST duplicates without generated
        assert_eq!(result.len(), 2, "Should find exactly 2 AST duplicates");

        // All should be ast_hash_001
        for dup in &result {
            assert_eq!(
                dup.hash, "ast_hash_001",
                "All results should have ast_hash_001"
            );
        }

        // Verify the two functions
        assert!(result.iter().any(|d| d.module == "MyApp.Accounts"
            && d.name == "format_name"), "Should include format_name");
        assert!(result.iter().any(|d| d.module == "MyApp.Controller"
            && d.name == "format_display"), "Should include format_display");
    }

    #[test]
    fn test_find_duplicates_ordering_by_hash_module_name() {
        let db = get_db();
        let result = find_duplicates(&*db, None, false, false, false)
            .expect("Query should succeed");

        // Verify ordering: by hash, then module, then name, then arity
        for i in 1..result.len() {
            let prev = &result[i - 1];
            let curr = &result[i];

            if prev.hash != curr.hash {
                assert!(
                    prev.hash < curr.hash,
                    "Results should be ordered by hash: {} < {}",
                    prev.hash,
                    curr.hash
                );
            } else if prev.module != curr.module {
                assert!(
                    prev.module < curr.module,
                    "Results with same hash should be ordered by module: {} < {}",
                    prev.module,
                    curr.module
                );
            } else if prev.name != curr.name {
                assert!(
                    prev.name < curr.name,
                    "Results with same hash/module should be ordered by name: {} < {}",
                    prev.name,
                    curr.name
                );
            } else {
                assert!(
                    prev.arity <= curr.arity,
                    "Results with same hash/module/name should be ordered by arity: {} <= {}",
                    prev.arity,
                    curr.arity
                );
            }
        }
    }

    #[test]
    fn test_find_duplicates_returns_correct_field_values() {
        let db = get_db();

        // Test AST duplicates field values
        let ast_result = find_duplicates(&*db, None, false, false, false)
            .expect("Query should succeed");

        // Find format_name duplicate (AST mode)
        let format_name = ast_result
            .iter()
            .find(|d| d.name == "format_name")
            .expect("format_name should be found");

        assert_eq!(format_name.hash, "ast_hash_001");
        assert_eq!(format_name.module, "MyApp.Accounts");
        assert_eq!(format_name.arity, 1);
        assert_eq!(format_name.line, 50);
        assert_eq!(format_name.file, "lib/my_app/accounts.ex");

        // Test source duplicates field values (use_exact=true)
        let src_result = find_duplicates(&*db, None, false, true, false)
            .expect("Query should succeed");

        // Find validate duplicate (source mode)
        let validate_service = src_result
            .iter()
            .find(|d| d.name == "validate" && d.module == "MyApp.Service")
            .expect("Service.validate should be found");

        assert_eq!(validate_service.hash, "src_hash_001");
        assert_eq!(validate_service.arity, 1);
        assert_eq!(validate_service.line, 70);
    }

    #[test]
    fn test_find_duplicates_module_filter_excludes_non_matching() {
        let db = get_db();
        // Service has source duplicates (not AST), so use_exact=true
        let result = find_duplicates(&*db, Some("Service"), false, true, false)
            .expect("Query should succeed");

        // Should find Service validate duplicates
        assert!(!result.is_empty(), "Should find Service duplicates");

        // All should be in Service module
        for dup in &result {
            assert_eq!(dup.module, "MyApp.Service");
        }
    }

    #[test]
    fn test_find_duplicates_nonexistent_module_returns_empty() {
        let db = get_db();
        let result = find_duplicates(&*db, Some("NonExistent"), false, false, false)
            .expect("Query should succeed");

        assert_eq!(result.len(), 0, "Should return empty for non-existent module");
    }

    #[test]
    fn test_find_duplicates_ast_and_source_mutually_exclusive() {
        let db = get_db();

        let ast_dups = find_duplicates(&*db, None, false, false, false)
            .expect("Query should succeed");
        let source_dups = find_duplicates(&*db, None, false, true, false)
            .expect("Query should succeed");

        // AST should return 4, source should return 2
        assert_eq!(ast_dups.len(), 4);
        assert_eq!(source_dups.len(), 2);

        // Verify they return different hashes
        let ast_hashes: Vec<_> = ast_dups.iter().map(|d| d.hash.as_str()).collect();
        let source_hashes: Vec<_> = source_dups.iter().map(|d| d.hash.as_str()).collect();

        // AST hashes should be ast_hash_001 and ast_hash_002
        assert!(ast_hashes.contains(&"ast_hash_001"));
        assert!(ast_hashes.contains(&"ast_hash_002"));

        // Source hashes should be src_hash_001
        assert!(source_hashes.iter().all(|h| *h == "src_hash_001"));
    }

    // ===== Mutation-killing tests for compound filter (line 82) =====
    //
    // Line 82: if !hash.is_empty() && !module.is_empty() && !name.is_empty() && !file.is_empty()
    //
    // Each test inserts a clause where exactly one field is empty while the others
    // (including the hash) are non-empty and match an existing duplicate hash.
    // The clause must be filtered OUT by the && chain. If any && is mutated to ||,
    // the clause leaks through and the result count increases, failing the assertion.

    #[test]
    fn test_find_duplicates_excludes_clause_with_empty_module() {
        let db = get_db_with_edge_cases();
        let result =
            find_duplicates(&*db, None, false, false, false).expect("Query should succeed");

        // Empty-module clause shares ast_hash_001 but must be filtered out.
        // Result count must be unchanged: still 4 (2 for ast_hash_001 + 2 for ast_hash_002).
        assert_eq!(
            result.len(),
            4,
            "Clause with empty module must be excluded from duplicates"
        );

        // No result should have an empty module
        for dup in &result {
            assert!(
                !dup.module.is_empty(),
                "No duplicate should have an empty module: {:?}",
                dup
            );
        }
    }

    #[test]
    fn test_find_duplicates_excludes_clause_with_empty_name() {
        let db = get_db_with_edge_cases();
        let result =
            find_duplicates(&*db, None, false, false, false).expect("Query should succeed");

        // Empty-name clause shares ast_hash_001 but must be filtered out.
        assert_eq!(
            result.len(),
            4,
            "Clause with empty name must be excluded from duplicates"
        );

        // No result should have an empty name
        for dup in &result {
            assert!(
                !dup.name.is_empty(),
                "No duplicate should have an empty name: {:?}",
                dup
            );
        }
    }

    #[test]
    fn test_find_duplicates_excludes_clause_with_empty_file() {
        let db = get_db_with_edge_cases();
        let result =
            find_duplicates(&*db, None, false, false, false).expect("Query should succeed");

        // Empty-file clause shares ast_hash_001 but must be filtered out.
        assert_eq!(
            result.len(),
            4,
            "Clause with empty file must be excluded from duplicates"
        );

        // No result should have an empty file
        for dup in &result {
            assert!(
                !dup.file.is_empty(),
                "No duplicate should have an empty file: {:?}",
                dup
            );
        }
    }

    // ===== Mutation-killing test for duplicate threshold (line 105) =====
    //
    // Line 105: .filter(|item| hash_counts.get(&item.hash).map_or(false, |count| *count > 1))
    //
    // A hash appearing exactly once must NOT be included. If > is mutated to >=,
    // the singleton leaks through.

    #[test]
    fn test_find_duplicates_excludes_singleton_hash() {
        let db = get_db_with_edge_cases();
        let result =
            find_duplicates(&*db, None, false, false, false).expect("Query should succeed");

        // The singleton clause has unique_hash_only_one which appears exactly once.
        // It must NOT appear in results — only hashes with count > 1 qualify.
        assert_eq!(
            result.len(),
            4,
            "Singleton hash (count=1) must not appear in duplicates"
        );

        assert!(
            !result.iter().any(|d| d.hash == "unique_hash_only_one"),
            "A hash that appears only once must not be in duplicates"
        );

        assert!(
            !result.iter().any(|d| d.name == "singleton_fn"),
            "singleton_fn must not appear in duplicates"
        );
    }
}
